# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30a2365c9efbeba6559632ac2e4379b7da70fafc38da6dd980ad8f475a90c3ac4081a9c67e48442ecf3106ab07372f6ae6030ded4a06d07b1803895c83784e92

test:
  secret_key_base: 744af4f1cf7bdca8883782a1a45972715596548e1c8b330993d2b04f14b2af78f2bda3c348f270f62960b9bec83e65f1b03481cbdb60eefc185733200bda8491

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
